server:
  port: 8585
logging:
  level:
    org.springframework.web: DEBUG
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5433/notifier"
    username: "notifier_user"
    password: "123456"
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5

app:
  configuration:
    interaction:
      sender-endpoint-type: "mockSenderInteraction"
